### ISSUE TITLE
Can't compile/build

### ISSUE THREAD

**Issue by narduin** [ueno-llc/newsletter#2]
Hello.

After installing the project, when running `npm start`, the index.html in the "build" folder displays a "panini error".

```
Panini Error

src/pages/index.hbs

Object.entries is not a function

Stack Trace:

args.reduce (/Volumes/Data/IT/_tests/ueno/newsletter/src/helpers/classnames.js:17:36)
Array.reduce (native)
Object.module.exports (/Volumes/Data/IT/_tests/ueno/newsletter/src/helpers/classnames.js:9:15)
Object.eval (eval at createFunctionContext (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:113)
main (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
Object.ret (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
Object.ret [as section] (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
Object.invokePartialWrapper [as invokePartial] (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
Object.eval (eval at createFunctionContext (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:14:28)
main (/Volumes/Data/IT/_tests/ueno/newsletter/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
```

Nothing seems wrong inside the terminal though.
Any idea ?

Thanks !

**Comment by gakimball** [comment]
You might be using an older version of Node—run `node -v` to find out. I think you need to be running at least Node 8.

**Comment by gakimball** [comment]
I added an `engines` field to the `package.json` to make this requirement a bit more obvious. 446f1c3af02b6a43065abf9aaf64ee3586329589

**Comment by narduin** [comment]
Thanks a lot that did it!
I was still using v6 for an old project :)

**Comment by gakimball** [comment]
Glad I could help :)
